version: '3.4'

services:
  eshopwcfservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__CatalogDBContext=Server=sql.data;Database=eShopDatabase;User Id=sa;Password=Pass@word;TrustServerCertificate=True
      - FeatureFlags__UseMockData=false
      - FeatureFlags__UseAzureStorage=false
      - FeatureFlags__UseAzureManagedIdentity=false
    ports:
      - "5113:8080"
    depends_on:
      - sql.data

  eshop.core.modernized:
    environment:
      - CatalogDBContext=Server=sql.data;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word
      - UseMockData=False
      - UseCustomizationData=False
      - UseAzureStorage=${ESHOP_USE_AZURE_STORAGE:-False}
      - UseAzureManagedIdentity=${ESHOP_USE_MANAGED_IDENTITY:-False}
      - StorageConnectionString=${ESHOP_AZURE_STORAGE_CONNECTION_STRING}
      - AppInsightsConnectionString=${APP_INSIGHTS_CONNECTION_STRING}
      - UseAzureActiveDirectory=${ESHOP_USE_AZURE_AD:-False}
      - AzureActiveDirectoryClientId=${AZURE_ACTIVE_DIRECTORY_CLIENT_ID}
      - AzureActiveDirectoryTenant=${AZURE_ACTIVE_DIRECTORY_TENANT}
      - PostLogoutRedirectUri=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP:-10.0.75.1}:5002/
    ports:
      - "5002:80"
    depends_on:
      - sql.data

  sql.data:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass@word
      - SA_PASSWORD=Pass@word
    ports:
      - "5433:1433"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Pass@word", "-C", "-Q", "select 1" ]
      interval: 5s
      retries: 20
