using System;
using System.Threading.Tasks;
using eShopCatalog.Contracts;

namespace eShopCatalogApi.Client
{
    /// <summary>
    /// Same shape as the <c>ICatalogService</c> interface generated by "Add Service Reference"
    /// for the legacy WCF service (sync + <c>*Async</c> pair per operation), so existing callers
    /// can switch to the HTTP API by changing only their <c>using</c> and construction code.
    /// </summary>
    public interface ICatalogService
    {
        CatalogItem FindCatalogItem(int id);
        Task<CatalogItem> FindCatalogItemAsync(int id);

        CatalogBrand[] GetCatalogBrands();
        Task<CatalogBrand[]> GetCatalogBrandsAsync();

        CatalogItem[] GetCatalogItems(int? brandIdFilter, int? typeIdFilter);
        Task<CatalogItem[]> GetCatalogItemsAsync(int? brandIdFilter, int? typeIdFilter);

        CatalogType[] GetCatalogTypes();
        Task<CatalogType[]> GetCatalogTypesAsync();

        int GetAvailableStock(DateTime date, int catalogItemId);
        Task<int> GetAvailableStockAsync(DateTime date, int catalogItemId);

        void CreateAvailableStock(CatalogItemsStock catalogItemsStock);
        Task CreateAvailableStockAsync(CatalogItemsStock catalogItemsStock);

        void CreateCatalogItem(CatalogItem catalogItem);
        Task CreateCatalogItemAsync(CatalogItem catalogItem);

        void UpdateCatalogItem(CatalogItem catalogItem);
        Task UpdateCatalogItemAsync(CatalogItem catalogItem);

        void RemoveCatalogItem(CatalogItem catalogItem);
        Task RemoveCatalogItemAsync(CatalogItem catalogItem);

        DiscountItem GetDiscount(DateTime day);
        Task<DiscountItem> GetDiscountAsync(DateTime day);
    }
}
